name: Auto PR from Theme Branch

on:
  # Trigger when changes are pushed to theme-branch
  push:
    branches:
      - theme-branch
  
  # Allow manual triggering from GitHub Actions tab
  workflow_dispatch:

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Check for changes
        id: changes
        run: |
          git diff --quiet origin/main...origin/theme-branch || echo "has_changes=true" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.changes.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Theme updates ready for main"
          body: |
            ## Automated Pull Request from Theme Branch
            
            This PR contains the latest theme changes ready to be merged into the main branch.
            
            ### Changes include:
            ```
            ${{ github.event.head_commit.message }}
            ```
            
            *Automated PR created by GitHub Actions*
          branch: theme-branch
          base: main
          labels: |
            theme
            automated-pr
          delete-branch: false
